//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseAPI.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public decimal id { get; set; }
        public decimal userid { get; set; }
        public decimal type { get; set; }
        public string path { get; set; }
        public Nullable<System.DateTime> last_modified { get; set; }
        public Nullable<decimal> modified_by { get; set; }
    
        public virtual User User { get; set; }
    }
}
